// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDbzfQFa2jn_7P1jTlyvWD6EbJM2WcxQrw',
    appId: '1:378781745237:web:06ac494e529361b7bd14dc',
    messagingSenderId: '378781745237',
    projectId: 'shaawl',
    authDomain: 'shaawl.firebaseapp.com',
    storageBucket: 'shaawl.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhA1-BV497FOTlxK1LaMbSj1hS0SRHZuE',
    appId: '1:378781745237:android:0960eab8d3a5e51cbd14dc',
    messagingSenderId: '378781745237',
    projectId: 'shaawl',
    storageBucket: 'shaawl.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABqmk32ZC9h_0GgaJJLU-6geUjizjqLY8',
    appId: '1:378781745237:ios:f713b7ecdf79aaa2bd14dc',
    messagingSenderId: '378781745237',
    projectId: 'shaawl',
    storageBucket: 'shaawl.appspot.com',
    iosClientId: '378781745237-l850q59nuur1cefckhst033rrgin02ul.apps.googleusercontent.com',
    iosBundleId: 'com.lmoc.prod.shawl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyABqmk32ZC9h_0GgaJJLU-6geUjizjqLY8',
    appId: '1:378781745237:ios:5cbfd1d7788887a1bd14dc',
    messagingSenderId: '378781745237',
    projectId: 'shaawl',
    storageBucket: 'shaawl.appspot.com',
    iosClientId: '378781745237-s0jhqv8sgqju4nni51ug2er7o2bhgksl.apps.googleusercontent.com',
    iosBundleId: 'com.example.shaawl',
  );
}
